### ISSUE TITLE
Update performance numbers in Readme

### ISSUE THREAD

**Issue by EwoutH** [toruseo/UXsim#104]
I think the performance numbers in the Readme could be updated on a few places, since https://github.com/toruseo/UXsim/pull/79 and https://github.com/toruseo/UXsim/pull/89 were merged:

https://github.com/toruseo/UXsim/blob/54bf92d39c0a4d17c1915d4b6dd54e84581180e2/README.md?plain=1#L23

https://github.com/toruseo/UXsim/blob/54bf92d39c0a4d17c1915d4b6dd54e84581180e2/README.md?plain=1#L36

https://github.com/toruseo/UXsim/blob/54bf92d39c0a4d17c1915d4b6dd54e84581180e2/README.md?plain=1#L175-L178

**Comment by toruseo** [comment]
thanks, will do later

**Comment by toruseo** [comment]
done

for the small-mid scale scenarios, the improvements are almost negligible, so I added mentioned to large scale one
