### ISSUE TITLE
Collect data only from part of network

### ISSUE THREAD

**Issue by EwoutH** [toruseo/UXsim#122]
I would be very nice if data (in the Analyzer) be filtered/selected to only collect data only from part of network. That could be an area like a neighbourhood or a subset selected based on properties, like all streets with a speed limit lower than 50 km/h.

The easiest way to implement it is probably to filter it like areas are currently filtered, by inputting a collection of nodes/edges.

In my specific case, I have a Network that has two parts: An outer supporting part (blue), which makes sure vehicles from out of the city enter at a proper point, and an inner part I actually want to measure (red). I have the Node `attribute` specified to if it's the inner or outer network, and I could also specify the Link `attribute` if needed.

![image](https://github.com/user-attachments/assets/87d352a9-3d10-409c-b5d6-89d1112ed857)

**Comment by toruseo** [comment]
Closing. See https://github.com/toruseo/UXsim/issues/143#issuecomment-2473026855 for the reason. Feel free to re-open.
