### ISSUE TITLE
Speed up `link_analysis_coarse`

### ISSUE THREAD

**Issue by EwoutH** [toruseo/UXsim#129]
Speed up `link_analysis_coarse`, since it takes up the majority of runtime.

![image](https://github.com/user-attachments/assets/f4bba1a7-b546-4842-b0b5-80d4d94b73f8)

@toruseo you can assign me to this issue.

**Comment by toruseo** [comment]
ok, plz try

but it is a single for-loop. Is there much room for improvement?

**Comment by EwoutH** [comment]
Vectorization can help in many cases.

But now that we only run it once #130 instead of multiple times another approaches, this is less high priority.

**Comment by toruseo** [comment]
Closing. See https://github.com/toruseo/UXsim/issues/143#issuecomment-2473026855 for the reason. Feel free to re-open.
