### ISSUE TITLE
Allow different vehicle lengths / weights

### ISSUE THREAD

**Issue by EwoutH** [toruseo/UXsim#142]
Currently, all vehicles have the same "length", or the same impact on the traffic flow/density. However, some vehicles are longer or smaller than others, and it would be interesting to allow.

I would propose a vehicle "scale" factor, which is `1.0` by default. If it's set smaller or larger on initialization, it has a larger or smaller impact on the traffic density. So a vehicle with `scale=2.0` is basically equivalent to 2 vehicles, etc.

**Comment by toruseo** [comment]
This is also impossible for the current framework. And this may be against the macroscopic philosophy.

**Comment by EwoutH** [comment]
Okay, thanks for getting back, then I will model it outside UXsim (by generating more or less vehicles).

**Comment by toruseo** [comment]
Since reaction time is a fixed global parameter in uxsim, it is not possible to directly model such AVs. But it may be reasonable to assume 1 vehicle in uxsim is actually 2 AVs that have 1/2 reaction time?

FYI: I will not able to work with uxsim for a while again
