### ISSUE TITLE
Future Plan: multi-lane link

### ISSUE THREAD

**Issue by toruseo** [toruseo/UXsim#33]
The current model assumes that all links are 1 lane. Furthermore, the reaction time of all drivers are the same. These mean that all links have more or less the same capacity.  It is not possible to model multi-lane links that have 2 or 3 times the capacity of 1-lane links. This is a theoretical limitation of the underlying model.

I plan to implement multi-lane with FIFO (no overtaking) in the future.

Workarounds for the current model:
- Create multiple links between same node pair; each link corresponds to each lane between the nodes. This is a reasonable solution. However, the analysis becomes tedious.
- Reduce `capacity_out` parameter of `Link`. In this way, we can place a bottleneck to the end of a link, so that capacities of links can vary significantly. However, it only reduce the capacity. Also, the jam propagation speed becomes too fast or slow.

**Comment by EwoutH** [comment]
I would really love to have this included!

**Comment by toruseo** [comment]
This will take some time as it requires changes to the fundamental simulation logic.

In the meantime, you can apply this workaround: 
> Create multiple links between same node pair; each link corresponds to each lane between the nodes. This is a reasonable solution. However, the analysis becomes tedious.

**Comment by erineifert-ida** [comment]
Wouldn't the jam density also be based on the number of lanes on a link?

**Comment by toruseo** [comment]
Correct. 

In the multilane update, I will implement a consistent model parameter definition.

**Comment by toruseo** [comment]
Simulation logic is implemented.  

Visualization needs to be updated.
