### ISSUE TITLE
Future Plan: modern packaging

### ISSUE THREAD

**Issue by toruseo** [toruseo/UXsim#43]
Modern packaging needs to be implemented instead of `setup.py`

**Comment by EwoutH** [comment]
Initial approach:
- https://github.com/toruseo/UXsim/pull/19

Let me know if you want any help with it!

**Comment by toruseo** [comment]
I think this is addressed now. Do you have any thoughts?

**Comment by EwoutH** [comment]
Looks great! Thanks for all the effort you're putting in!
