### ISSUE TITLE
Deploy docs pages (automated)

### ISSUE THREAD

**Issue by EwoutH** [toruseo/UXsim#66]
It seems like the docs page deployment hasn't been triggered in some time: https://github.com/toruseo/UXsim/deployments/github-pages

Is this expected behavior? Or should it run on each push to `main`, or each release?

**Comment by toruseo** [comment]
For some reason, the docs is at https://toruseo.jp/UXsim/docs/ 
I have updated it too.

To avoid confusion, I put redirecting html at https://toruseo.jp/UXsim/
