### ISSUE TITLE
GPS type csv output?

### ISSUE THREAD

**Issue by apiszcz** [toruseo/UXsim#78]
Reviewed the Analyzer methods, I did not see a method to output a GPS type output log csv with all the vehicles x,y,time,id. Did i miss a capability ?

**Comment by toruseo** [comment]
This is not implemented.

I will consider it in the future update.

**Comment by toruseo** [comment]
Now you can generate GPS-like log using `W.analyzer.gps_like_log_to_pandas()`

**Comment by apiszcz** [comment]
Thank you! Will review.
