### ISSUE TITLE
Speed up `homogeneous_DUO_update`

### ISSUE THREAD

**Issue by EwoutH** [toruseo/UXsim#84]
After the amazing speedup in #53 / #79, the performance bottleneck has shifted to `homogeneous_DUO_update`, which now takes up around two thirds of the runtime.

![image](https://github.com/user-attachments/assets/d8ed03d6-eafb-4f86-9e6f-3c244c1bceae)

The nested loop over all destinations and all links probably takes up the most runtime. If that can be vectorized that would improve general UXsim performance with up to ~3x.

https://github.com/toruseo/UXsim/blob/8c67dd03546e09193ab1e337fb7682f7fa8b2e79/uxsim/uxsim.py#L1303-L1326

**Comment by toruseo** [comment]
Thanks for testing!

Vectorization may be possible. I will consider it later.

Please let me know if you come up with any ideas.

**Comment by EwoutH** [comment]
I think vectorization and using efficient data structures are the most logical to try initially. Some things that might be worthwhile trying:
- Save the route preferences (`route_pref`) as a matrix. Since it will be very sparse (I think?), maybe try a [dok_matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.dok_matrix.html) from scipy.sparse.
- Vectorize the weight update.
- Maybe try if we can skip some links or do some lazy calculations based on graph theory principles.

**Comment by toruseo** [comment]
Sounds reasonable. `RouteChoice.route_pref` is indeed sparse. Lazy calculation will be fine, but just skipping is not very good as it will lose generality.

Can you try?

**Comment by EwoutH** [comment]
On vacation for another two weeks. After that I could give it a shot!

Feel free to make a first attempt in the meantime, if you have the chance!

**Comment by toruseo** [comment]
Well, Claude Sonnet implemented this one instantaneously. In a large scale scenario, the computation time was reduced from 10 sec to less than 1 sec. 

I will merge it into the main after some testing and improvements.

**Comment by EwoutH** [comment]
Awesome! It’s insane how well these models are getting. I did a quick attempt with GPT-4o, but not that successful. Maybe I need to try 3.5 Sonnet more often!

**Comment by EwoutH** [comment]
On this network:
```
simulation setting:
 scenario name: MyUXsimWorld2
 simulation duration:	 7200 s
 number of vehicles:	 107325 veh
 total road length:	 2166279 m
 time discret. width:	 25 s
 platoon size:		 25 veh
 number of timesteps:	 288
 number of platoons:	 4293
 number of links:	 3272
 number of nodes:	 1545
```
uxsim 1.3.1 performance
```
      time| # of vehicles| ave speed| computation time
       0 s|        0 vehs|   0.0 m/s|     0.00 s
     300 s|     8575 vehs|   6.2 m/s|     8.12 s
     600 s|    17350 vehs|   5.8 m/s|    14.17 s
     900 s|    24775 vehs|   5.9 m/s|    20.19 s
    1200 s|    32200 vehs|   5.4 m/s|    26.20 s
    1500 s|    39025 vehs|   5.2 m/s|    32.27 s
```
uxsim 1.4.0 performance
```
      time| # of vehicles| ave speed| computation time
       0 s|        0 vehs|   0.0 m/s|     0.00 s
     300 s|     9400 vehs|   6.1 m/s|     1.77 s
     600 s|    17475 vehs|   5.7 m/s|     3.13 s
     900 s|    25550 vehs|   5.7 m/s|     4.55 s
    1200 s|    32900 vehs|   5.6 m/s|     6.04 s
    1500 s|    39900 vehs|   5.5 m/s|     7.59 s
```
Another very impressive 4x speedup!

This configuration took over 20 minutes before #53 was resolved, now under a minute!

A new profile also shows that `homogeneous_DUO_update` now takes less than 10% of runtime, down from around two-thirds before #89 was merged.

![image](https://github.com/user-attachments/assets/e845bafa-1aea-4225-aaf9-631bd2a197a0)
