### ISSUE TITLE
Future Plan: add "hard deterministic mode"

### ISSUE THREAD

**Issue by toruseo** [toruseo/UXsim#99]
In a local discussion with my colleague, it was suggested that a simulation mode that does not use any random element would be useful for some specific purposes such as numerical validation of theoretical models. Such mode can be implemented by adding alternative route choice and merging models. I will implement this in the future update.

**Comment by EwoutH** [comment]
Are you planning on using random seeds, or another approach?

**Comment by toruseo** [comment]
Doing deterministic (or reproducible) simulation by fixing seeds is already implemented, so this is something different.

For example in "hard deterministic mode", when merging, vehicles from a link with the largest `merge_priority` value will be always prioritized. Also, vehicles will always choose the shortest path. In the default mode, they are all stochastic (i.e., randomly chosen by weights) and not always convenient for analysis that need strict predictability.

**Comment by EwoutH** [comment]
Right, so basically removing all stochastic elements from the model.

**Comment by toruseo** [comment]
implemented
